### ISSUE TITLE
Getting Stack Overflow

### ISSUE THREAD

**Issue by umeshkumhar** [hashicorp/terraform-plugin-codegen-openapi#132]
### tfplugingen-openapi CLI version

tfplugingen-openapi module: v0.3.0

### OpenAPI Spec File

```YAML
https://gist.github.com/umeshkumhar/97c7888fbcf6f294bb54210e0faec918
```

### Generator Config

```YAML
provider:
  name: backupdr

resources:
  slp:
    create:
      path:  /slp
      method: POST
    read:
      path:  /slp
      method: GET
```

### Expected Behavior

It should have generated provider spec json. 

### Actual Behavior

This just executed and later on get killed due to OOM (i guess). in some iteration it shows stack overflow error. The activity monitor states that it consumes 70+GB memory, please find the attached screenshot below. Seems like its failing during Marshalling the openapi file.
<img width="817" alt="Screenshot 2024-01-29 at 10 16 38" src="https://github.com/hashicorp/terraform-plugin-codegen-openapi/assets/8029688/c24f0d20-5b69-4532-9758-aea011d80ef5">
<img width="905" alt="Screenshot 2024-01-29 at 10 19 40" src="https://github.com/hashicorp/terraform-plugin-codegen-openapi/assets/8029688/e1724ee9-9c92-46b6-b165-5db747981392">

### Additional Information

Please suggest some workaround this.. if we can still generate some provider spec json for at least /slt, /sla, /slp. to kickstart.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
