### ISSUE TITLE
Petstore workflow example from code-gen documentation is generating incorrect schema

### ISSUE THREAD

**Issue by austinvalle** [hashicorp/terraform-plugin-codegen-openapi#152]
> Originally discovered here: https://discuss.hashicorp.com/t/sdk-provider-development-anyone-ever-used-code-generation-or-other-tools-to-simplify-their-provider-development/20301/8

### tfplugingen-openapi CLI version

tfplugingen-openapi module: v0.3.0

### OpenAPI Spec File

```YAML
https://petstore3.swagger.io/api/v3/openapi.json
```

### Generator Config

```YAML
provider:
  name: petstore
resources:
  pet:
    create:
      path: /pet
      method: POST
    read:
      path: /pet/{petId}
      method: GET
    schema:
      attributes:
        aliases:
          petId: id
```

### Expected Behavior

N/A

### Actual Behavior

Recently, the swagger JSON example we use in our [workflow example](https://developer.hashicorp.com/terraform/plugin/code-generation/workflow-example#generate-pet-schema-from-openapi-spec) from https://petstore3.swagger.io/api/v3/openapi.json has been updated to include a couple recursions of the `category` property. This results in generating invalid provider code when attempting to build:

![image](https://github.com/hashicorp/terraform-plugin-codegen-openapi/assets/8650838/0f9dde19-21f7-42ea-89ab-48ffac3829b8)

Apparently this is related to a known issue and is currently being investigated: https://github.com/swagger-api/swagger-petstore/issues/125

### Additional Information

https://developer.hashicorp.com/terraform/plugin/code-generation/workflow-example#generate-pet-schema-from-openapi-spec

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
