### ISSUE TITLE
Ensure that `description` is populated if at least one description exists between merged operations

### ISSUE THREAD

**Issue by austinvalle** [hashicorp/terraform-plugin-codegen-openapi#48]
> This could be a can of worms, as the merging functionality hasn't been refactored yet (maybe should be, as a part of this)

## Background
Given the following OAS + config, in the context of a data source:
```jsonc
    "paths": {
        "/pet/{petId}": {
            "get": {
                "tags": [
                    "pet"
                ],
                "summary": "Find pet by ID",
                "description": "Returns a single pet",
                "operationId": "getPetById",
                "parameters": [
                    {
                        "name": "petId",
                        "in": "path",
                        "description": "ID of pet to return",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
...
    "components": {
        "schemas": {
            "Pet": {
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int64",
                        "example": 10
                    },
```
```yaml
data_sources:
  pet:
    read:
      path: /pet/{petId}
      method: GET
    merge_options:
      param_matches:
        petId: id
```

You'll generate the following IR, with a description:
```json
{
	"name": "id",
	"int64": {
		"computed_optional_required": "required",
		"description": "ID of pet to return"
	}
},
```
-----------------
However, in the context of a resource, with the same OAS, you don't get a description in the resulting IR:
```yaml
resources:
  pet:
    create:
      path: /pet
      method: POST
    read:
      path: /pet/{petId}
      method: GET
    update:
      path: /pet
      method: PUT
    delete:
      path: /pet/{petId}
      method: DELETE
    merge_options:
      param_matches:
        petId: id
```
```json
{
	"name": "id",
	"int64": {
		"computed_optional_required": "computed_optional"
	}
},
```

## Proposal
This is occurring because during the merging process (currently a very simple merge of `n` schemas across request body/response body, etc.), there is no functionality to preserve descriptions across multiple merges. 

We should refactor and update the merging process to have the following behavior after merge:
- If multiple attributes exist that all have a populated `description`, keep the highest precedence `description` (current behavior)
- If the highest precedence attribute doesn't have a populated `description`, take the next highest precedence `description`
