### ISSUE TITLE
Consider adjusting collection data sources default name

### ISSUE THREAD

**Issue by austinvalle** [hashicorp/terraform-plugin-codegen-openapi#83]
## Background
After #78 added support for collection data sources (by automatically creating a root `SetNested` or `Set` attribute), we decided to automatically set the name of the attribute to be the same as the data source name.

This may not be desired if the data source name has multiple words like `aws_secretsmanager_secrets`.

## Possible solutions
- Adjust the attribute name to split on underscore and take the last word
- Add a configuration option to the generator config to allow a custom name:

#### Example
```yaml
data_sources:
  petmanager_pets:
    read:
      path: /pet/findByStatus
      method: GET
    schema:
      collection_name: pets 
```
